services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-delivery-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/livrasion_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
      OSRM_URL: http://host.docker.internal:5000
    restart: unless-stopped
